spring:
  datasource:
    name: playground
    url: jdbc:mysql://localhost:3309/playground?characterEncoding=utf-8&useSSL=false&serverTimezone:GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#开启驼峰命名法
  mybatis-plus:
    #mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.happy.pojo
    global-config:
      db-config:
        id-type: AUTO
    configuration:
      map-underscore-to-camel-case: true
